# This is a basic workflow to help you get started with Actions

name: Build and Push

# Controls when the action will run. 
on:
  repository_dispatch:
    types: [trigger_build]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Download binary
        run:  wget https://github.com/syncthing/syncthing/releases/download/${{ steps.getversion.outputs.version }}/syncthing-linux-arm-${{ steps.getversion.outputs.version }}.tar.gz && tar -xf *tar.gz --strip 1

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@e1b7f96249f2e4c8e4ac1519b9608c0d48944a1f
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          # List of build-time variables
          build-args: SYNCTHING_RELEASE=${{ steps.getversion.outputs.version }}
          # List of target platforms for build
          platforms: linux/arm/v7,linux/arm/v6
          # Push is a shorthand for --output=type=registry
          push: true
          # List of tags
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-syncthing:${{ steps.getversion.outputs.version }},${{ secrets.DOCKERHUB_USERNAME }}/docker-syncthing:latest
          
